httpListener:
  host: "localhost"
  port: "8082"
  path: "/api/v1/*"

database:
  url: "jdbc:postgresql://ep-young-salad-ai503ad3-pooler.c-4.us-east-1.aws.neon.tech:5432/hb_sales_db?sslmode=require&channel_binding=require"
  driver: "org.postgresql.Driver"
  user: "neondb_owner"