#%RAML 1.0 DataType
properties:
  method?:
    description: Action to be performed in Database
    example: SELECT
    type: string
  query?:
    description: The encoded query to be run in Database
    example: c2VsZWN0KiBmcm9tIEVtcGxveWVl
    type: string