#%RAML 1.0
title: Heritage Bookshop Database System API
description: This System API is integrattetd with Heritage Bookshop Database
version: 1.0
mediaType: application/json
protocols:
  - HTTPS
uses:
  data-types-library: /library/datatypes-library.raml

/sql-operation:
  post:
    displayName: Database Call
    description: Perform Fetch/Insert/Update/Delete actions on DB Tables based on the input
    body:
      application/json:
        type: data-types-library.DatabaseSqlOperationRequestSchema
        example: !include database_sql_operation/examples/database_request_example.json
    responses:
      200:
        body:
          application/json:
            type: data-types-library.DatabaseSqlOperationResponseSchema
            example: !include database_sql_operation/examples/database_response_example.json
      400:
        description: Error is a bad request on the payload, querystring, or headers.
        body:
          application/json:
      500:
        description: Something went wrong with the request.
        body:
          application/json:
            
            
